word = input('Digite algo : ')
print(f'tipo primitivo : {type(word)}')
print(f'composto por espaços : {word.isspace()}')
print(f'é numérico : {word.isnumeric()}')
print(f'é alfabético : {word.isalpha()}')
print(f'é numérico : {word.isalnum()}')
print(f'está em maiúsculas : {word.isupper()}')
print(f'está em minúsculas : {word.islower()}')
print(f'está capitalizada : {word.istitle()}')
